/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-02-22 07:52:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.etc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.iei.member.model.vo.Member;

public final class map_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1677051961006L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1676337261927L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.iei.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=osh0s8np34&submodules=geocoder\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    	Member m = (Member)session.getAttribute("m");
    
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 구글 아이콘 -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- jquery -->\r\n");
      out.write("    <script src=\"/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("    <!-- 기본 CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/default.css\" />\r\n");
      out.write("    <!-- 기본 js -->\r\n");
      out.write("    <script src=\"/js/default.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <header>\r\n");
      out.write("      <div class=\"site-logo\">\r\n");
      out.write("        <a href=\"/\">GOLD KIWI</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <nav>\r\n");
      out.write("        <ul class=\"navi\">\r\n");
      out.write("          <li><a href=\"/noticeList.do?requestPage=1\">공지사항</a></li>\r\n");
      out.write("          <li><a href=\"/boardList.do?requestPage=1\">자유게시판</a></li>\r\n");
      out.write("          <li><a href=\"/ajax.do\">AJAX</a></li>\r\n");
      out.write("          <li><a href=\"/photoList.do\">사진게시판</a></li>\r\n");
      out.write("          <li>\r\n");
      out.write("			<a href=\"#\">메뉴-5</a>\r\n");
      out.write("            <ul class=\"sub-navi\">\r\n");
      out.write("              <li><a href=\"/email.do\">email</a></li>\r\n");
      out.write("              <li><a href=\"/map.do\">지도</a></li>\r\n");
      out.write("              <li><a href=\"/pay.do\">결제</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("           </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <div class=\"header-link\">\r\n");
      out.write("      ");
if(m == null){ 
      out.write("\r\n");
      out.write("        <button class=\"btn bc11 modal-open-btn\" target=\"#login-modal\">SIGN IN</button>\r\n");
      out.write("        <a class=\"btn bc11\" href=\"/signupFrm.do\">SIGN UP</a>\r\n");
      out.write("      ");
}else{ 
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <a class=\"btn bc11\" href=\"/mypage2.do?memberId=");
      out.print(m.getMemberId() );
      out.write('"');
      out.write('>');
      out.print(m.getMemberName() );
      out.write("</a>\r\n");
      out.write("      \r\n");
      out.write("      <a class=\"btn bc11\" href=\"/logout.do\">LOGOUT</a>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    ");
if(m == null) {
      out.write("\r\n");
      out.write("    <div id=\"login-modal\" class=\"modal-bg\">\r\n");
      out.write("      <div class=\"modal-wrap\">\r\n");
      out.write("        <div class=\"modal-head\">\r\n");
      out.write("          <h2>SIGN IN</h2>\r\n");
      out.write("          <span class=\"material-icons close-icon modal-close\">close</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"/signin.do\" method=\"post\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <div class=\"input-box\">\r\n");
      out.write("          	<label for=\"signId\">아이디</label>\r\n");
      out.write("          	<input type=\"text\" name=\"signId\" id=\"signId\" class=\"input-form\" placeholder=\"아이디입력\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-box\">\r\n");
      out.write("          	<label for=\"signPw\">비밀번호</label>\r\n");
      out.write("          	<input type=\"password\" name=\"signPw\" id=\"signPw\" class=\"input-form\" placeholder=\"비밀번호입력\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-box link-box\">\r\n");
      out.write("          	<a href=\"#\">아이디/비밀번호 찾기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-foot\">\r\n");
      out.write("          <button type=\"submit\" class=\"btn bc11\">로그인</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn bc1 modal-close\">취소</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("	<div class=\"page-conent\">\r\n");
      out.write("		<div class=\"page-title\">지도 API</div>\r\n");
      out.write("		<h2>1. 다음 주소찾기 API</h2>\r\n");
      out.write("		<div class=\"address-wrap\">\r\n");
      out.write("			<input type=\"text\" name=\"posstcode\" id=\"postcode\" class=\"input-form\" style=\"width : 200px; display : inline-block;\"readonly>\r\n");
      out.write("			<button class=\"btn bc1\" onclick=\"searchAddr();\">주소찾기</button>\r\n");
      out.write("			<input type=\"text\" name=\"address\" id=\"address\" class=\"input-form\" readonly>\r\n");
      out.write("			<input type=\"text\" name=\"detailAddress\" id=\"detailAddress\" class=\"input-form\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<h3>2. 네이버지도</h3>\r\n");
      out.write("		<div id=\"map\" style=\"width: 100%; height: 500px;\"></div>\r\n");
      out.write("		<button onclick=\"loadMap();\" class=\"btn bc1\">조회한 곳으로 지도 이동</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("		const map = new naver.maps.Map(\"map\",{\r\n");
      out.write("			center : new naver.maps.LatLng(37.533837,126.896836),\r\n");
      out.write("			zoom : 17,\r\n");
      out.write("			zoomControl : true,\r\n");
      out.write("			zoomControlOptions : {\r\n");
      out.write("				position : naver.maps.Position.TOP_RIGHT,\r\n");
      out.write("				style : naver.maps.ZoomControlStyle.SMALL\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		const marker = new naver.maps.Marker({\r\n");
      out.write("			position : new naver.maps.LatLng(37.533837,126.896836),\r\n");
      out.write("			map : map\r\n");
      out.write("		}); // 지도에 marker를 붙여주는거\r\n");
      out.write("		let contentString = [\r\n");
      out.write("			\"<div class='iw_inner'>\",\r\n");
      out.write("			\"	<h3>KH정보교육원</h3>\",\r\n");
      out.write("			\" 	<p>서울시 영등포구 선유2로 57 이레빌딩 19F A강의장</p>\",\r\n");
      out.write("			\"</div>\"\r\n");
      out.write("		].join(\"\"); //marker클릭하면 정보가 나오게\r\n");
      out.write("		let infoWindow = new naver.maps.InfoWindow();\r\n");
      out.write("		\r\n");
      out.write("		//marker에 클릭이벤트 추가\r\n");
      out.write("		naver.maps.Event.addListener(marker, \"click\", function(e){\r\n");
      out.write("			infoWindow = new naver.maps.InfoWindow({\r\n");
      out.write("				content : contentString\r\n");
      out.write("			});\r\n");
      out.write("			//생성된 infoWindow를 map의 marker 위치에 생성\r\n");
      out.write("			infoWindow.open(map, marker);\r\n");
      out.write("		});\r\n");
      out.write("		//map에 클릭이벤트 추가\r\n");
      out.write("		naver.maps.Event.addListener(map,\"click\",function(e){\r\n");
      out.write("			marker.setPosition(e.coord);//클릭한 위치로 마커 이동\r\n");
      out.write("			map.setCenter(e.coord); //클릭한 곳을 센터로\r\n");
      out.write("			if(infoWindow.getMap()){ //정보창이 지도 위에 올라가있으면 \r\n");
      out.write("				infoWindow.close();\r\n");
      out.write("			}\r\n");
      out.write("			//위경도를 통해서 해당 위치의 주소를 알아내기(reverseGeocode)\r\n");
      out.write("			naver.maps.Service.reverseGeocode({ //주소를 주면 위경도를 구해주는건 Geocode의 반대\r\n");
      out.write("				location : new naver.maps.LatLng(e.coord.lat(),e.coord.lng())\r\n");
      out.write("			}, function(status, response){\r\n");
      out.write("				if(status != naver.maps.Service.Status.OK){\r\n");
      out.write("					return alert(\"주소를 찾을 수 없습니다\");\r\n");
      out.write("				}\r\n");
      out.write("				console.log(response);\r\n");
      out.write("				const address = response.result.items[1].address;\r\n");
      out.write("				contentString = [\r\n");
      out.write("					\"<div class='iw_inner'>\",\r\n");
      out.write("					\" 	<p>\"+address+\"</p>\",\r\n");
      out.write("					\"  	</div>\"\r\n");
      out.write("				].join(\"\");\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("		});\r\n");
      out.write("		function searchAddr(){\r\n");
      out.write("		   new daum.Postcode({\r\n");
      out.write("		       oncomplete: function(data) {\r\n");
      out.write("		    	   console.log(data);\r\n");
      out.write("		    	   $(\"#postcode\").val(data.zonecode);\r\n");
      out.write("		    	   $(\"#address\").val(data.address);\r\n");
      out.write("		    	   $(\"detailAddress\").focus();\r\n");
      out.write("		           // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.\r\n");
      out.write("		           // 예제를 참고하여 다양한 활용법을 확인해 보세요.\r\n");
      out.write("		       }\r\n");
      out.write("		   }).open();\r\n");
      out.write("		};\r\n");
      out.write("		function loadMap(){\r\n");
      out.write("			const addr = $(\"#address\").val();\r\n");
      out.write("			naver.maps.Service.geocode({\r\n");
      out.write("				address : addr\r\n");
      out.write("			},function(status, response){\r\n");
      out.write("				if(status === naver.maps.Service.Status.ERROR){ //type까지 일치하는지 보려고 자바스크립트는 1==\"1\"하면 true가 나오기 때문에 type까지 보려면 1===\"1\"로 해야한다\r\n");
      out.write("					return alert(\"조회 에러\");\r\n");
      out.write("				}\r\n");
      out.write("				console.log(response);\r\n");
      out.write("				const lng = response.result.items[1].point.x;//경도\r\n");
      out.write("				const lat = response.result.items[1].point.y;//위도\r\n");
      out.write("				//위경도 객체\r\n");
      out.write("				const latlng = new naver.maps.LatLng(lat,lng);\r\n");
      out.write("				map.setCenter(latlng);\r\n");
      out.write("				marker.setPosition(latlng);\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("      <div class=\"footer-content\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("          <li><a href=\"#\">개인정보취급방침</a></li>\r\n");
      out.write("          <li><a href=\"#\">인재채용</a></li>\r\n");
      out.write("          <li><a href=\"#\">제휴문의</a></li>\r\n");
      out.write("          <li><a href=\"#\">인스타그램</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>Made by LeeYunSu</p>\r\n");
      out.write("        <p>\r\n");
      out.write("          KH정보교육원 당산지원 A강의장 수업자료입니다. 무단복제를 허용하지\r\n");
      out.write("          않습니다.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
